name: VinctusNative

options:
  deploymentTarget:
    iOS: '17.0'
  createIntermediateGroups: true

configs:
  DebugDev: debug
  DebugStaging: debug
  DebugProd: debug
  ReleaseProd: release

settings:
  base:
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    SWIFT_VERSION: 5.0

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.0.0

targets:
  VinctusNative:
    type: application
    platform: iOS
    deploymentTarget: '17.0'
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vinctus.native
        INFOPLIST_FILE: Resources/Info.plist
      configs:
        DebugDev:
          VINCTUS_ENV: dev
        DebugStaging:
          VINCTUS_ENV: staging
        DebugProd:
          VINCTUS_ENV: prod
        ReleaseProd:
          VINCTUS_ENV: prod
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseFunctions
      - package: Firebase
        product: FirebaseStorage

  VinctusNativeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: VinctusNative

schemes:
  VinctusNative-Dev:
    build:
      targets:
        VinctusNative: all
    run:
      config: DebugDev
    test:
      config: DebugDev
      targets:
        - VinctusNativeTests

  VinctusNative-Staging:
    build:
      targets:
        VinctusNative: all
    run:
      config: DebugStaging
    test:
      config: DebugStaging
      targets:
        - VinctusNativeTests

  VinctusNative-Prod:
    build:
      targets:
        VinctusNative: all
    run:
      config: DebugProd
    test:
      config: DebugProd
      targets:
        - VinctusNativeTests
